name: Release & Publish

on:
  push:
    branches:
      - b2-main

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: false

  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUBLISH_PAT }}
      - name: Configure Git User
        run: |
          git config --global user.email "ci@b2network"
          git config --global user.name "ci-$GITHUB_ACTOR"
      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@b2network'
      - name: Install modules
        run: yarn install
      - name: Build and Publish to GitHub Packages
        run: yarn lerna publish patch --yes
