name: Release

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: false